### ISSUE TITLE
CLI: add ability to do operations against Apps with friendly names instead of AppID GUID

### ISSUE THREAD

**Issue by altsang** [ExpressGateway/express-gateway#260]

**Comment by stanislaw-glogowski** [comment]
### CLI options proposal:
https://docs.google.com/document/d/17i_Blpwes_iPfiTlc96phCoEomRZWiUGOogmEM82Hp0/edit?usp=sharing

**Comment by XVincentX** [comment]
This is being paused because of #499

**Comment by XVincentX** [comment]
In order to provide the same feature in the same way search by user has been provided, we would need to add a new key in Redis that has been missing so far for all the applications. 

Although we could add it and provide the features, all legacy users won't be able to search by application name for the legacy.

1. Implement a different (and probably inefficient system — get all apps and manually filtering them)
2. Provide another migration script to take all the applications and index them properly.

@altsang @DrMegavolt

**Comment by DrMegavolt** [comment]
yes the new key is what is expected. I believe original PR already has it. but in general it works same way as for users. 
1) no, just another relation field should work 
2) yes, a migration to build such index
