### ISSUE TITLE
Spec: Admin: extend API to include policy config within pipeline

### ISSUE THREAD

**Issue by altsang** [ExpressGateway/express-gateway#387]

**Comment by DrMegavolt** [comment]
apiPipeline 
     - p1: ...
     - p2: ...
            (- p2.5: ...) trying to insert
     - p3: ...

So API should not only configure policy but also have understanding position and pipeline name. 

That is not the end. Policy contains condition\action pairs that need to be managed 
p2: [
      - cond1/action1 
      - cond2/action2
]

OUT of scope:
both of them have some schema to validate. (because it will make changes to plugin framework and introduce validation engine in the API, this could be 2 additional stories)

**Comment by DrMegavolt** [comment]
the solution https://tools.ietf.org/html/rfc6902 
PATCH /pipelines/name

**Comment by DrMegavolt** [comment]
the new proposal doc 
https://docs.google.com/document/d/1qgeYckdTuoQE24wZrju40jef92nTeNO0nIQXyfsCA38/edit#
