### ISSUE TITLE
JWT Plugin: verification

### ISSUE THREAD

**Issue by altsang** [ExpressGateway/express-gateway#419]
_From @altsang on September 10, 2017 21:34_

see #30 for part 1 of the JWT use case

**Comment by altsang** [comment]
EPIC: 
- for planning poker purposes - please assign a point size
- this is needs to be broken down into engineering user stories - please prefix with `JWT Plugin:`

### Background Info
- per our plugin naming convention, this will be the first iteration of jwt plugin -  `express-gateway-plugin-jwt`
- JWT RFC - https://tools.ietf.org/html/rfc7519
- this is an auth mechanism to EG, to keep consistent with the ecosystem and the interfaces already adopted, we should use `Passport` based middleware (i.e. `passport-jwt`
- library for generating JWT - `jsonwebtoken`
- Passport JWT overview - https://blog.jscrambler.com/implementing-jwt-using-passport/
- super helpful debugger - https://jwt.io

### New JWT Policy and Plugin Registration
The plugin will introduce a new auth policy - JWT.
- plugin is registered under `system.config.yml` in the `plugins:` section 
- system wide parameters are specified underneath its entry
  * querystring param that contain JWT - `jwt` = default
  * claim used containing the JWT key, `iss` = default
  * registered claims that can be verified
    - `iss`-  in the case of EG being the provider, the parameter specified above is used to identify the key
    - `sub` - TBD, should understand the use case for this claim further
    - `aud` - TBD, however, if `sub` is used, then `aud` must also be verified
    - `exp` - EG can verify this claim
    - `nbf` - EG can verify this claim
    - `jti` -  an extra layer of security to prevent replay, probably not necessary for 1st iteration of JWT
- a JWT policy can be declared in the `gateway.config.yml` in the `policies:` section which will allow the JWT policy to be used within a pipeline

### New Credential Type
The plugin will extend EG credential management by introducing a new credential type known as JWT - (i.e. `jwt`, just like `basic`, `oauth2` etc)

### JWT Credential Type 
The new JWT credential type will need to contain the following:
- keyId - auto generated (please refer to how `key-auth` works in EG for more info on how keys are generated in pairs - id and secret)
- verification algorithm: `HS256`, `RS256`, or `ES256`
- rsa_public key: for `RS256`/`ES256`
- keySecret:  auto generated (note: if the algo is `H256`/`ES256`)

### Admin API and CLI extensions
- you need to be create a `jwt` credential type via CLI
- parameters:
  * which `algo` to use (see above)
  * RSA public key, supported options below
    - string key itself
    - path to PEM file (used for `RS256` / `ES256`)
    - bonus: openssl extraction of pub key directly from X.509 cert
- you need to be able to delete a `jwt` credential

### Issues/Blockers
- JWTs can be multiple and nested, what to do? start simple with single for our own reference implementation
- 1 JWT type credential per consumer? or is this something more like `key-auth`?
- how to type in EG scopes into the JWT payload
-  the token and credential services in EG must be extended via the plugin - this was planned for iteration 2 of the plugin framework development plan

**Comment by XVincentX** [comment]
`CLIExtensions` are still missing in the gateway. Credentials generation is going to be blocked. I'll keep going with the validation anyway. @altsang

**Comment by XVincentX** [comment]
I've been looking at this and there are multiple things we should clarify.

## CLI Extension
ExpressGateway hasn't (yet) any way to extend the CLI. This means that, if we go with a plugin, we won't be able to generate a new JWT secret per consumer or eventually let the user provide a private key.

## Token storage
I think that just storing the JWT in a query string would not fit all use cases. I do believe we should at least provide lookup by `Header`, `Query String` and `Cookie (with HttpOnly flag)`

## Token generation
Should the gateway have the ability to generate the token? Kong, for example, does not. It's just verifying the signature and some claims, and then appending some Http headers (with username, scopes and stuff like that). Any further verification is up to somebody else. We should clarify this, eventually.

**Comment by altsang** [comment]
maintainers decided to iterate on this - release JWT as core plugin first and then have story to refactor out as own plugin - #

**Comment by XVincentX** [comment]
@altsang @kevinswiber @DrMegavolt 

I need a clarification here, since when you say JWT I see multiple scenarios:

### EG as a token signature verifier

The gateway is providing an `id` and a `secret` (or eventually and id and a certificate file, it does not really matter), using the CLI. These are used respectively as the `issuer` and the signing secret for JWT produced by somebody else (such as an external identity server). The gateway verifies the signature and it's simply forwarding the requests attaching the same token and attaching the `consumerId` header, as it can't assume anything about the payload itself. This is the scenario that [Kong is offering](https://getkong.org/plugins/jwt/). In this case, *our scopes* do not really make sense, although can still offer and check those, eventually.

### EG as a token issuer

2. Express Gateway has scope as well, therefore it can also issue a JWT token using the informations we have in the gateway (such as `consumerId`, `consumerName`, the `scopes` array and so on and so forth). Question is, how do we want to issue such token? One way would be through the `oAuth2` plugin. If so, how should this token look like (in terms of payload)?

**Comment by DrMegavolt** [comment]
I would suggest to implement simple scenario when you generate JWT tokens 
like here http://kong:8001/consumers/{consumer}/jwt (ADMIN API + CLI)
and policy itself is configured to verify those tokens (has secret etc. configured in config file)

And scopes can be just custom claim if we need to support them 
-----
because there advanced scenarios. like verify token in third party endpoint. 
or make oauth2 use JWT tokens instead of current uuid
