### ISSUE TITLE
host versus hostname: need consistency

### ISSUE THREAD

**Issue by altsang** [ExpressGateway/express-gateway#432]
the `admin:` section and `apiEndpoints:` use `host:` versus `hostname:` should pick one

- [ ] update generators
- [ ] update docs
- [ ] update CLI
- [ ] update tests

**Comment by ravikp7** [comment]
Hey @XVincentX , what should be picked? `host` or `hostname` ?

**Comment by XVincentX** [comment]
@ravikp7 I believe we should go for `host`. It's important to keep the compatibility with the old configuration file so we should suppor both for a while, emit a warning and remove it in EG 2.0.

**Comment by ravikp7** [comment]
Hmm, makes sense for the compatibility. As per my understanding, tasks are

- Replace `hostname` with `host` in the in the generator files, so that new setups would have updated config:
  - `./bin/generators/gateway/templates/getting-started/config/gateway.config.yml`
  - `./bin/generators/gateway/templates/basic/config/gateway.config.yml`
  - `./bin/eg-generator.js`

- Add `host` support with `hostname` in `./lib/rest/index.js` and emit warnings when `hostname` is found on admin config

- In the schema `./lib/config/schemas/gateway.config.json`, add `host` under admin and leave `hostname` as it is for now

- Replace `hostname` with `host` in `./lib/config/gateway.config.yml`. I also want to know, when this config is used?

- Update `tests` and `docs` according to above changes

And later in `EG 2.0`, remove references to `hostname` completely.

@XVincentX Please let me know if I'm missing something.

**Comment by XVincentX** [comment]
You've got it. The additional task would then be to update our documentation website http://github.com/expressGateway/express-gateway.io — but we usually do that after the changes have been merged in the `master` branch.

Does that make sense to you?

**Comment by ravikp7** [comment]
Yeah, got it.Thanks :)
