### ISSUE TITLE
policy default params: implementation of one of the proposed variants

### ISSUE THREAD

**Issue by altsang** [ExpressGateway/express-gateway#511]

**Comment by DrMegavolt** [comment]
@altsang As I understand Variant A is a chosen approach
https://docs.google.com/document/d/1TjAEORHPqbPUa6H9dTlEHxfW3fWiiBlMJPh030JCyx0/edit#heading=h.sj2xx5prpxqb

In Gateway.config 
```

policies:
 - proxy
 - key-auth
```
Become
``` 
policies:
 - proxy:
	defaultActionParams:
		changeOrigin:true
 - key-auth # current syntax still valid (string)
```

**Comment by altsang** [comment]
Yes - I'm fine with this, looking back I would've liked `global.config.yml`
instead of just `system.config.yml` but oh well.

It's consistent with the app concerns being in one YAML



On December 5, 2017 at 3:50:28 AM, Serhii Kuts (notifications@github.com)
wrote:

@altsang <https://github.com/altsang> As I understand Variant A is a chosen
approach
https://docs.google.com/document/d/1TjAEORHPqbPUa6H9dTlEHxfW3fWiiBlMJPh030JCyx0/edit#heading=h.sj2xx5prpxqb

In Gateway.config


policies:
 - proxy
 - key-auth

Become

policies:
 - proxy:
        defaultActionParams:
                changeOrigin:true
 - key-auth # current syntax still valid (string)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ExpressGateway/express-gateway/issues/511#issuecomment-349281705>,
or mute the thread

**Comment by XVincentX** [comment]
@altsang @kevinswiber 

My two cents on the topic (I know I'm late in the party, I haven't been able to jump on this sooner because of the conference. Feel free to ignore if it's too late).

Keep in mind we have JSON schema in place, and it's handling parameters validation as well as default parameters. As part as #571 I'm trying to use JSON Schema for everything about validation and default parameters, so we should really push for it as much as possible.

The ideal way to tame this would be to let the people to partially modify the JSON Schema of the target policy/condition and change its default parameters, by using a [JSON Patch](http://jsonpatch.com/)

So the **IDEAL** flow would be

1. The user has a policy with the following schema:
```javascript
const schema = {
  type: 'object',
  properties: {
    name: {
      type: 'string',
      default: 'hello'
    }
  }
}
```

And he wants to change the default value to `hey`. Then he would need to apply somehow this JSON Patch to the gateway:

```json
[ {
  "op" : "replace",
  "path" : "/properties/name/default",
  "value" : "bar"
} ]
```

The gateway would load the patch, apply it to the JSON Schema and then load the policy/plugin.

Double win. We don't write any code to handle this, validation is still there and the policy code can entirely focus on doing its job.

I am ok to to use an alternative syntax to make it user friendly (you'll decide on that guys), but I'd try at least to make sure that the end result is a JSON Patch that'll be applied to the original policy/condition schema, and not handle these things directly into the code.

Does that make sense?

**Comment by DrMegavolt** [comment]
I believe this is too complex behavior
users just need the "bar" part of your example

As side effect you can disable validation for some really required fields.

**Comment by XVincentX** [comment]
> I believe this is too complex behavior

Yes, I agree that writing a JSON Patch object for an user might be hard.

In fact I stated:

> I am ok to to use an alternative syntax to make it user friendly (you'll decide on that guys), but I'd try at least to make sure that the end result is a JSON Patch that'll be applied to the original policy/condition schema, and not handle these things directly into the code.

**Comment by DrMegavolt** [comment]
I planned to merge defaults with user defined settings before running schema validation. 
so you will be safe of writing defaults that doesn't make sense

it should be relatively simple code (1 line ? `params = Object.assign({}, defaults[policyName], actionParams)`)

**Comment by altsang** [comment]
this needs to be documented, the functionality is there and examples need to be written to show overriding in the `gateway.config.yml`

**Comment by XVincentX** [comment]
This is now handled in a doc section. I've also suggested it to a guy on Gitter and he seems to be happy.
