### ISSUE TITLE
Question about passing the logger down to the policy

### ISSUE THREAD

**Issue by matcha440** [ExpressGateway/express-gateway#634]
Some thoughts I was having while reading the activity on ExpressGateway/express-gateway-plugin-rewrite#9 and it seems like there should be a logger being passed into policy middleware.  I could possibly pass the logger in pluginContext down to the policy, but it's the plugin logger and not the policy logger.  But that is of course if I want to hook into EG's logger instead of choosing my own.

I'm pretty sure if the official plugins are going to ultimately reside within their own repos so that does make me curious if there's a plan for this yet or not.

**Comment by DrMegavolt** [comment]
@jbalsip  you mean passing `logger` variable (the policy one)  here 
https://github.com/ExpressGateway/express-gateway/blob/feature/custom-logout-return-url/lib/policies/index.js#L30  ?

**Comment by jbalsip** [comment]
Yes, I think so.

**Comment by DrMegavolt** [comment]
looks reasonable to me. PR is welcome

**Comment by jbalsip** [comment]
@DrMegavolt I'll have some ideas on this before too long I think.  I do want a little more clarification, though.  I had noted that the arguments for setting up a policy get passed in as part of the pipeline here:
https://github.com/ExpressGateway/express-gateway/blob/39ca89e4d31b2f9e0cc7d0898683c555b9d0ae2b/lib/gateway/pipelines.js#L134

Originally I was thinking of passing the logger in at that point in the code.  But with the code you've referenced would you be thinking to just args.push to pass in the logger or did you have something different in mind?

**Comment by XVincentX** [comment]
This is a interesting topic, and although I do not have (yet) a solution here, I see two scenarios.

1. Pass somehow the objects we need down to the plugin, and then go from there.

2. (Maybe unique to Javascript) — Another possible way to achieve that would be to require the services directly from Express-Gateway. So basically instead of passing these parameters in the policy, you could do directly from the plugin: 

```javascript
const logger = require('express-gateway/lib/logger')
logger.policy('Message you want to log');
```

In this way, you require what you need, no matter if we provide it or not from a plugin. CommonJS makes sure the result is cached and it's a singleton — so no harms.

The only problem I see, is that if one day we will change the file location, everybody would break. I do not see this happening, but it's a possibility. Theoretically this could be also be resolved using CommonJS aliases. Do you think would it be a viable way, if properly documented? @jbalsip

**Comment by DrMegavolt** [comment]
a no-no for  `require('express-gateway/lib/logger')` it is a dependency on EG. and EG should be devDependency as max 

technically each policy can have an individual logger, not generic policy. but I would just pass `policy` logger
