### ISSUE TITLE
Can't remove Firstname or lastname from User model

### ISSUE THREAD

**Issue by Replica-** [ExpressGateway/express-gateway#658]
The documentation states the following:
https://www.express-gateway.io/docs/consumer-management/

**Note: _username_ property is used by Express Gateway. Please avoid changing it since it may cause unexpected behaviour.**

This would lead me to believe that I could remove the other fields, eg. _firstName_ and _lastName_ fields from the user model schema json without consequence, however, this is not the case:

The response via adding a user from cli "eg users create":
✖ data should have required property 'firstname'
 
The expected outcome: Removal of all fields except _username_, should result in successful user generation.

**Comment by XVincentX** [comment]
Hey @Replica- 
that paragraph is not stating that you can avoid `firstname` and `lastname` properties — they are required because of the user JSON Schema.

What is claimed there is that, basically, you can modify the JSON Schema to add an remove the properties you want but `username`, as that one is used internally by Express-Gateway.

In order to make your example work correctly, you would need to modify the json schema and remove `username` and `lastname` from the `required` array.

Does that answer your question? Feel free to reopen if needed.

**Comment by Replica-** [comment]
Thanks @XVincentX! appreciate the quick response, you are absolutely correct. I just realised my config file wasn't being reloaded automatically due to a syntax error somewhere, yet the CLI was picking up the most recent changes to the user model file 😢

**Comment by XVincentX** [comment]
Feel free to stop by in the gitter channel for faster responses.
