### ISSUE TITLE
OAuth2: add third party introspection URL

### ISSUE THREAD

**Issue by altsang** [ExpressGateway/express-gateway#703]
https://tools.ietf.org/html/rfc7662

**Comment by sivabudh** [comment]
@altsang Once this issue has been implemented, does it mean that Express Gateway will support Social OAuth providers like Google now?

**Comment by sivabudh** [comment]
Interesting and thanks. 

I would like to share our exploration so far. We used NGINX previously as a L7 proxy for 2 "microservices" on the backend. Then we came across Kong and its promise to centralize authentication. We found out that Kong didn't support Google OAuth, and that not all features were available.

Then we came across Express Gateway, which we would have preferred to use, but it seems the support for 3rd party OAuth2 server is not yet supported.

We did also look at Tyk and are now checking out Ambassador (based on EnvoyProxy).

Just wanted to share my story from the perspective of someone looking for an API Gateway to use in production.

CC: @psmithip

**Comment by altsang** [comment]
Since you have an interest in this use case and maybe have this as a
requirement can we continue this over email? al @ lunchbadger.com thx


On May 7, 2018 at 10:58:39 PM, Sivabudh Umpudh (notifications@github.com)
wrote:

Interesting and thanks.

I would like to share our exploration so far. We used NGINX previously as a
L7 proxy for 2 "microservices" on the backend. Then we came across Kong and
its promise to centralize authentication. We found out that Kong didn't
support Google OAuth, and that not all features were available.

Then we came across Express Gateway, which we would have preferred to use,
but it seems the support for 3rd party OAuth2 server is not yet supported.

We did also look at Tyk and are now checking out Ambassador (based on
EnvoyProxy).

Just wanted to share my story from the perspective of someone looking for
an API Gateway to use in production.

CC: @psmithip <https://github.com/psmithip>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ExpressGateway/express-gateway/issues/703#issuecomment-387293583>,
or mute the thread

**Comment by XVincentX** [comment]
Note: the current package we're using for oauth2 does not provide any built in introspection implementation. We might need to handle that by ourselves

**Comment by XVincentX** [comment]
Hey @sivabudh 

this is great, thank you very much for the efforts.

I've reached you on Gitter to discuss how we can proceed with this. Looking forward to collaborate with you!

**Comment by DrMegavolt** [comment]
https://github.com/jaredhanson/passport-twitter

**Comment by XVincentX** [comment]
- Introspection support for our oAuth2 policy could be done using; https://github.com/valudio/passport-token-introspection

- Introspection client for external oAuth2 servers could be done using: https://www.npmjs.com/package/token-introspection (note — they're using a different http client that might be a problem for us)

- I haven't been able to find any generic oAuth2 client policy, only "provider-specific-one" that do not fulfill all the providers in the world.

**Comment by DrMegavolt** [comment]
https://www.npmjs.com/package/passport-oauth2 should be ok for the standard scenario. 
but we should allow typing random passport strategy and just load it.

**Comment by DrMegavolt** [comment]
just to reiterate, not everybody is using standard scheme. sometimes really specific plugin is used (pretty much any social provider) so in this case 
in customers project, one can do `npm i passport-twitter`

and have policy `passport-auth`

```
passport-auth:
     provider: passport-twitter # real npm package name 
     authSettings:
           CLIENT_ID ... # or whatever is required by provider 
```
Note some minor tricks like how strategy is exposed:
 `passport-auth` will internally `passport.use(require('package.name')(...))`
or ``passport.use(new require('package.name')(...))`` or whatever style is used by lib.

**Comment by XVincentX** [comment]
So, I've been looking a little bit more into this today, here's my findings:

> We should allow typing random passport strategy and just load it.

We can talk about it, although it seems to be a little bit out of scope.

---

I've been exploring the `passport-oauth2` package and I am afraid this won't solve the problem we're exposing here.

This package seems to be a basic package that needs to be subclassed in order to create a provider-specific implementation. You can see this looking at some functions [that](https://github.com/jaredhanson/passport-oauth2/blob/master/lib/strategy.js#L275) [are](https://github.com/jaredhanson/passport-oauth2/blob/master/lib/strategy.js#L307) [empty](https://github.com/jaredhanson/passport-oauth2/blob/master/lib/strategy.js#L291) by default, and should be filled by an implementer.

Moreover, this seem to cover just the oAuth2 dance part; the token validity verification is completely skipped, and relying again on a real implementation to make that work.

### Rant to the world

Which, by the way, *is correct*. This is simply happening because everybody in the world decided to put authentication expectations on a protocol that was not supposed to do so.

### End of the rant

Interestingly enough, I've [checked](https://github.com/jaredhanson/passport-github/blob/master/lib/strategy.js#L64) [some](https://github.com/jaredhanson/passport-google-oauth2/blob/master/lib/strategy.js#L54) [providers](https://github.com/jaredhanson/passport-twitter/blob/master/lib/strategy.js#L115) and it seems like everybody has his own way to check the token validity and get informations from it. Nobody is really following the **introspection** standard. I guess it's because this part came later, when everybody was already in production with the oAuth2 spec

**Comment by DrMegavolt** [comment]
> We can talk about it, although it seems to be a little bit out of scope.
I'm not talking about auto install. It just requires already installed package

and for the most cases Strategies are exposed in some combination of
```
p  = require('my-passport-auth-that-doesnt-care-about-standard') 
// variant 1, package is a strategy and must be called with new
passport.use (new p()) 
// 2 package package is a strategy 
passport.use(p()) 
// 3 Strategy is some property in p
passport.use(p.Strategy()) 
passport.use(new p.Strategy()) 

and it is trivial to write a wrapper to that shape if package authors were really creative

This approach allows to plugin almost *any* auth provider. 
Imagine how you could connect some things like LDAP, any social network with no code.     

and see, all strategies populate `req.user` so you can link them to internal users by relating foreign id
`req.user[action.id_property_name]`  to internal user

**Comment by XVincentX** [comment]
@altsang This thing cannot be a plugin as we proposed yesterday. Unfortunately in order to keep consistency with the other auth policies (in particular the [`passthough` parameter](https://www.express-gateway.io/docs/policies/basic-authorization/#example)) — we need access to the `commonAuthCallback` which is clearly not accessible from a plugin. I've opened an issue and marked it as a technical debt one (#746)

Let's discuss this during the next standup but I am starting to feel that this thing of supporting somehow any provider is not something we can solve right now. EG is still too coupled with its internals. I suggest we just focus on one thing — Pure introspection support — so we can close this and move on.

If providers do not support the standard, it's their problem, not ours.
