### ISSUE TITLE
eg apps list and eg users list return incomplete results or empty

### ISSUE THREAD

**Issue by Tiberriver256** [ExpressGateway/express-gateway#749]
It seems that the SCAN in the findAll method for both the application dao and the user dao only does a single call instead of a full iteration which works when testing but not when your database grows outside of the default query range for SCAN.

The SCAN should be called again and again until the return cursor is 0 to guarantee the search is complete (called a 'full iteration'). From the [docs](https://redis.io/commands/scan):

> As you can see the SCAN return value is an array of two values: the first value is the new cursor to use in the next call, the second value is an array of elements.
> 
> Since in the second call the returned cursor is 0, the server signaled to the caller that the iteration finished, and the collection was completely explored. Starting an iteration with a cursor value of 0, and calling SCAN until the returned cursor is 0 again is called a full iteration.

I will put in a PR for what is working as a fix in our environment.

**Comment by XVincentX** [comment]
Hey @Tiberriver256,

We do not return the whole set from the Admin API on purpose. In case of a huge list of users or applications, this would blow up the gateway. Given the Admin API and the gateway itself live in the same process, we do want to minimize it's impact as much as possible.

That's why we leverage the Redis cursors to paginate through the result.

Basically, for you, this means:

- Make your first call to the Admin API:
`curl http://localhost:9876/users`

- Grab the `nextKey` value from the response:

`{"users":[],"nextKey":0}`

- Use it in the following user call:

`curl  http://localhost:9876/users?start=nextKeyValue`

That should fulfill your use case.
I think we do not have the feature properly documented in our website. I'm going to check and open an issue there if it's the case.


In case it's not or you need more clarification, feel free to reopen the issue or jump in our Gitter channel.

Thanks!

**Comment by Tiberriver256** [comment]
Ah, so maybe this is a bug in the cli consuming the API then?

**Comment by XVincentX** [comment]
This might be. I'll reopen the issue!

**Comment by Tiberriver256** [comment]
Ah, I think I found it. This should be checking for a nextKey then and calling again if there is one correct?

https://github.com/ExpressGateway/express-gateway/blob/76d32c1650ce29fbe03a0dc69d4cbe2e0eca7c01/admin/users.js#L35-L42

**Comment by XVincentX** [comment]
Correct!

**Comment by XVincentX** [comment]
@Tiberriver256 I proposed a solution for this problem in #762 pull request. If you have some time I'd appreciate your input there. Thanks!

**Comment by Tiberriver256** [comment]
That works for me. Thank you sir.

**Comment by altsang** [comment]
@XVincentX has this been reviewed? been so long

**Comment by XVincentX** [comment]
The pull request has been reviewed some time ago. I addressed all the comments and pinging Kevin for another round of review — but no answer yet.
